### ISSUE TITLE
API Resource spec

### ISSUE THREAD

**Issue by Noah-Huppert** [Noah-Huppert/flock#9]
It would be nice to create a system where you define a resource as being at a certain url and maybe give it some metadata and then the server and client systems work together to retrieve, cache, update, delete the resources whilst allowing the programmer to use a nice seeming API (aka make this app super RESTful).

Resource properties:
- type
    - Resource type ex., `user`, `post`, `event`
- url
    - Url resource is located at
- data
    - Resource data

Resource actions:
- Get
- Update
- Create
- Delete

**Comment by Noah-Huppert** [comment]
Resource Identifier
===
Fields:
- `type`
    - Resource type
    - Client and Server will also both contain a global list of registered data schemas.
    - When a schema is registered a type name is also associated with that schema.
    - So whenever a resource is received the client/server must look at the `type` field first to determine which schema to use.
    - Also determines which database table (IndexedDB/Postgres) the client/server should query
- `id`
    - Unique identifier of resource in db tables
- `etag`
    - Deep ETag of resource

Serialization:  
`type@id#etag`

Example use in sample server JSON response:
```
{
    "car": {
        "id": "car@56#33a64df551425fcc55e4d42a148795d9f25f89d4",
        "user_id": "user@89#67cc558793dc145f89d45f5af34565d9f2e4d42a",
        "seats": "5",
        "make": "Chevy",
        "model": "Truckitytruck",
        "color": "#000000",
        "loc_lat": "-1",
        "loc_long": "-1"
    },
    "errors": []
}
```
As you can see the `car.id` and `car.user_id` fields are `Resource Identifier`s. These identifiers provide clients with enough information to determine how to retrieve a referenced resource (In the above example how to retrieve a `user` with the `id` of `89`) and an `ETag` to determine if their version of a cached resource is the version referenced in the request.

**Comment by Noah-Huppert** [comment]
# RDFS with JSON-LD integration
In order to create a more explorable API and store data for future ML usage in a useful way the resource system will use `JSON-LD` to serve data. Models will still be served with the same keys as those in the database but will have a `@context` directive to specify how to map keys to standard RDF schemas. When possible the resource system will try to use standard `schema.org` and `foaf` schemas. 

The previously described resource identifier is now integrated as `URI`s. `URI`s for Squad Up resources include a fragment which represents the resource's `ETag`. If no fragment is present the API assumes the client has never retrieved the resource before. Maybe keep track of perceived client side cache misses by keeping track of API requests for resources that don't have a fragment (Per API Token as well to maybe spot greedy clients, maybe devs who are using API to poke around but making too many requests to be a good tenant).

Example JSON-LD response:
```
{
    "car": {
        "@context": "https://squad-up.com/api/v1/resources/car/context.jsonld`,
        "@id": "https://squad-up.com/api/v1/resources/car/56#33a64df551425fcc55e4d42a148795d9f25f89d4",
        "@type": "https://schema.org/Vehicle",
        "user_id": "https://squad-up.com/api/v1/resources/user/89#67cc558793dc145f89d45f5af34565d9f2e4d42a",
        "seats": "5",
        "make": "Chevy",
        "model": "Truckitytruck",
        "color": "#000000",
        "loc_lat": "-1",
        "loc_long": "-1"
    },
    "errors": []
}
```

**Comment by Noah-Huppert** [comment]
Now that I have done a bunch of research and thinking, here is what I need to do next: 

- [ ] Define entire system requirements
- [ ] Break resource system into layers
- [ ] Identify actions for each layer
- [ ] Implement layers

**Comment by Noah-Huppert** [comment]
**General purpose:** Serve API resources in an intelligent way which lends itself to an offline experience. 

# Functional requirements
- Store data on client
- Schema definition
    - An API resource's schema can be split into a couple layers since the resource system is made up of serveral technologies that aim to solve different goals
        - Map model keys to common RDF schema (With JSON-LD Context)
        - Validate model (With JSON Schema schema)
    - These two seperate schemas must be changed together or a system must automatically change / generate them.
- Exchange data in versioned schema
    - Exchange data in JSON-LD
    - Define schema with [JSON Schema](http://json-schema.org/)
- Auto generate machine files

# Schema definitation

**Comment by Noah-Huppert** [comment]
# Functional Requirements V2
- Get, Create, Update, Delete Models.
- Notify Client of Model change.
- Cache.
- Client & Server Interface.
- Access Control.
- Use common RDF vocab.

**Comment by hsluoyz** [comment]
Hi, I'm the author of [casbin](https://github.com/casbin/casbin). It is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

So please consider using casbin when Squad Up  implements access control security. Also let me know if there's any question:)

**Comment by Noah-Huppert** [comment]
Hey hsluoyz, I'll be sure to take a look at [casbin](https://github.com/casbin/casbin). This Resource System definitely needs an access control component. I really only picked [Ladon](https://github.com/ory/ladon) because I had starred it from Hacker News a couple months back. And we haven't even committed any effort to using it yet.

I'll be sure to give your repository a good look and consider using it.
